spring:
  datasource:
    url: jdbc:mysql://database:3306/eventus?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: 4a3b6702b7144887a0dd28312c36d31e
    password: 90e72b30d0be44f1966fc51fc9b1b4f5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

io:
  github:
    xnovo3000:
      eventus:
        admin-password: 8627341495ce4ae9b771fd5b53740785
        page-size: 12

logging:
  level:
    root: warn
    web: error
    sql: error