spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/eventus?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PSWD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

io:
  github:
    xnovo3000:
      eventus:
        admin-password: admin
        page-size: 24

logging:
  level:
    root: debug
    web: debug
    sql: debug
    io:
      github:
        xnovo3000:
          eventus: debug