spring:
  datasource:
    url: jdbc:mysql://database:3306/eventus?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: 4a3b6702b7144887a0dd28312c36d31e
    password: 90e72b30d0be44f1966fc51fc9b1b4f5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

io:
  github:
    xnovo3000:
      eventus:
        user_page_size: 18
        event_page_size: 9

logging:
  level:
    root: error