spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/eventus?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PSWD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

io:
  github:
    xnovo3000:
      eventus:
        user_page_size: 24
        event_page_size: 12
        old_unapproved_event_removal_task_rate: 300000